# These are supported funding model platforms

github: [ jasonw4331 ] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: jasonw4331
custom: https://www.buymeacoffee.com/jasonw4331