--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/SpectreZone
build-by-default: true
projects:
  SpectreZone:
    path: ""
    icon: "icon.png"
    lint: false
    excludeDirs:
      - tests
      - .github
      - build
      - phpstan
    excludeFiles:
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
    libs:
      - src: jasonwynn10/libCustomPack/libCustomPack
        version: ^0.1.1
...
