--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonw4331/SpectreZone
build-by-default: true
projects:
  SpectreZone:
    path: ""
    icon: "icon.png"
    excludeDirs:
      - .github
    excludeFiles:
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
      - phpstan.neon.dist
      - phpstan-baseline.php
      - .php-cs-fixer.php
    libs:
      - src: jasonw4331/libCustomPack/libCustomPack
        version: ^1.0.1
...
