name: SpectreZone
main: jasonw4331\SpectreZone\SpectreZone
src-namespace-prefix: jasonw4331\SpectreZone
version: 1.0.3
api: 4.16.0
author: jasonw4331
description: "Creates a Spectre Zone dimension based on the MC Java Random Things Mod"
depend:
 - Customies
softdepend:
 - NativeDimensions