  #####                                                  #######
 #     #  #####   ######   ####   #####  #####   ######       #    ####   #    #  ######
 #        #    #  #       #    #    #    #    #  #           #    #    #  ##   #  #
  #####   #    #  #####   #         #    #    #  #####      #     #    #  # #  #  #####
       #  #####   #       #         #    #####   #         #      #    #  #  # #  #
 #     #  #       #       #    #    #    #   #   #        #       #    #  #   ##  #
  #####   #       ######   ####     #    #    #  ######  #######   ####   #    #  ######
#--------------------------------------------------------------------------------------------------
Chunk Offset: 1
Default Height: 4